### ISSUE TITLE
Problem Extracting Audio-Only Embeddings using AV-HuBERT

### ISSUE THREAD

**Issue by david-gimeno** [facebookresearch/av_hubert#104]
I am implementing a script to extract video-only, audio-only and audio-visual embeddings using a AV-HuBERT checkpoint. Specifically, I am using the one fine-tuned to the AVSR downstream task: ```large_noise_pt_noise_ft_433h.pt```.

- I preprocessed the videos and wavs based on the code found in `hubert_dataset.py`.
- Everything works fine for the video-only (lipreading) embeddings, obtaining a tensor of shape ```(nframes, 1024)```
- However, when trying to extract the audio-only embeddings (i.e., setting the video source to ```None```), I am getting the error displayed below. My audio input tensors to the model has the shape ```(1, 67, 26) ~ (batch, nframes, mfcc)```. I do not understand why the ```self.proj``` (defined in class ```SubModel``` in line 317 of ```avhubert/hubert.py```) is expecting a dimension of ```104```. 
- **What am I doing wrong?** Thanks in advance :)

```
Checkpoint: fine-tuned
Traceback (most recent call last):                                                                                                                                                    
  File "extract_avhubert_embeddings.py", line 244, in <module>
    audio_embeddings = extract_audio_embeddings(audio_feats, args.avhubert_checkpoint_path, cuda_device = args.cuda_device)
  File "extract_avhubert_embeddings.py", line 124, in extract_audio_embeddings
    audio_embeddings, _ = model.extract_finetune(source={'video': None, 'audio': audio_feats}, padding_mask=None, output_layer=None)
  File "/home/dgimeno/phd/sensitive-avsr/av_hubert/avhubert/hubert.py", line 707, in extract_finetune
    features_audio = self.forward_features(src_audio, modality='audio') # features: [B, F, T]
  File "/home/dgimeno/phd/sensitive-avsr/av_hubert/avhubert/hubert.py", line 544, in forward_features
    features = extractor(source)
  File "/home/dgimeno/anaconda3/envs/sensitive_avsr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dgimeno/phd/sensitive-avsr/av_hubert/avhubert/hubert.py", line 330, in forward
    x = self.proj(x.transpose(1, 2))
  File "/home/dgimeno/anaconda3/envs/sensitive_avsr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dgimeno/anaconda3/envs/sensitive_avsr/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [1, 67] but got: [1, 104].
```

**Comment by david-gimeno** [comment]
I got it! That 104 refers to the number of features composing the audio input tensor. In order to make the model work with audio stream data, we have to stack every 4 frames into 1 in order to better align the acoustic cues to the visual ones. This meant adding:

```
stack_order_audio = 4
audio_feats = stacker(audio_feats, stack_order_audio)
```
in my implementation when processing the audio waveform. In this way, I was able to obtain an acoustic input tensor of shape ```(time,104)```, and then I just only needed to add a _fake_ batch dimension of 1 sample and do a permutation to obtain the resulting shape of ```(batch, 104, time)``` as following:`

audio_feats.unsqueeze(dim=0).permute(0,2,1).cuda()`

In my opinion, I was confused because in

https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert_dataset.py#L287C13-L287C71

that ```self.stack_order_audio``` variable is set to 1 by default but it is for sure modified in some configuration file.

Please excuse the inconvenience. Best regards,

David
