### ISSUE TITLE
Are there fine-tuned models for ASR provided?

### ISSUE THREAD

**Issue by 18445864529** [facebookresearch/av_hubert#12]
I downloaded the fine-tuned model from the "Finetuned Models for Visual Speech Recognition" section with the name "base_lrs3_30h.pt" and ran the decoding script for it. 

While I was able to decode the model trained by myself, when decoding the downloaded checkpoint (aforementioned), I got the following error. Is this because the checkpoint I downloaded is for lip-reading but not ASR or some other reason?
Thanks!

```
Traceback (most recent call last):                                                                                            
  File "infer_s2s.py", line 285, in hydra_main
    distributed_utils.call_main(cfg, main)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "infer_s2s.py", line 90, in main
    return _main(cfg, h)
  File "infer_s2s.py", line 221, in _main
    hypos = task.inference_step(
  File "/gs/hs0/tga-tslab/bowen/av_hubert/fairseq/fairseq/tasks/fairseq_task.py", line 527, in inference_step
    return generator.generate(
  File "/gs/hs0/tga-tslab/bowen/Anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/sequence_generator.py", line 188, in generate
    return self._generate(sample, **kwargs)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/sequence_generator.py", line 258, in _generate
    encoder_outs = self.model.forward_encoder(net_input)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/sequence_generator.py", line 772, in forward_encoder
    return [model.encoder.forward_torchscript(net_input) for model in self.models]
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/sequence_generator.py", line 772, in <listcomp>
    return [model.encoder.forward_torchscript(net_input) for model in self.models]
  File "/gs/hs0/tga-tslab/bowen/av_hubert/fairseq/fairseq/models/fairseq_encoder.py", line 55, in forward_torchscript
    return self.forward_non_torchscript(net_input)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/fairseq/fairseq/models/fairseq_encoder.py", line 62, in forward_non_torchscript
    return self.forward(**encoder_input)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/hubert_asr.py", line 386, in forward
    x, padding_mask = self.w2v_model.extract_finetune(**w2v_args)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/hubert.py", line 704, in extract_finetune
    features_audio = self.forward_features(src_audio, modality='audio') # features: [B, F, T]
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/hubert.py", line 541, in forward_features
    features = extractor(source)
  File "/gs/hs0/tga-tslab/bowen/Anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gs/hs0/tga-tslab/bowen/av_hubert/avhubert/hubert.py", line 327, in forward
    x = self.proj(x.transpose(1, 2))
  File "/gs/hs0/tga-tslab/bowen/Anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gs/hs0/tga-tslab/bowen/Anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/gs/hs0/tga-tslab/bowen/Anaconda3/envs/avhubert/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3000x26 and 104x768)
```

**Comment by chevalierNoir** [comment]
Hi,

The models in "Finetuned Models for Visual Speech Recognition"  are fine-tuned for lip reading. For ASR, you need to fine-tune the pre-trained models in "pre-trained model" table. The models in "Finetuned Models for Audio-Visual Speech Recognition" can also be used directly for ASR.
