### ISSUE TITLE
fairseq-hydra-train with single-node multiple-gpu training

### ISSUE THREAD

**Issue by stoneyang** [facebookresearch/av_hubert#21]
Hi, there,

When started training on my machine with eight gpus with the command provided on README as follows:
```
fairseq-hydra-train --config-dir /path/to/conf/ --config-name conf-name \
  task.data=/path/to/data task.label_dir=/path/to/label \
  model.label_rate=100 hydra.run.dir=/path/to/experiment/pretrain/ \
  common.user_dir=`pwd`
```
it did started -- but only use device 0 with the following message:
```
[2022-02-15 19:25:02,218][fairseq.utils][INFO] - ***********************CUDA enviroments for all 1 workers***********************
[2022-02-15 19:25:02,218][fairseq.utils][INFO] - rank   0: capabilities =  6.0  ; total memory = 15.899 GB ; name = Tesla P100-PCIE-16GB
[2022-02-15 19:25:02,218][fairseq.utils][INFO] - ***********************CUDA enviroments for all 1 workers***********************
[2022-02-15 19:25:02,219][fairseq_cli.train][INFO] - training on 1 devices (GPUs/TPUs)
[2022-02-15 19:25:02,219][fairseq_cli.train][INFO] - max tokens per device = 1000 and max sentences per device = None
[2022-02-15 19:25:02,220][fairseq.trainer][INFO] - Preparing to load checkpoint checkpoints/checkpoint_last.pt
[2022-02-15 19:25:02,221][fairseq.trainer][INFO] - No existing checkpoint found checkpoints/checkpoint_last.pt
[2022-02-15 19:25:02,221][fairseq.trainer][INFO] - loading train data for epoch 1
```

Even if I added `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 ` before the command, the rest gpus are still in idle. 

Any suggestions to solve this?

Thanks in advance.

**Comment by stoneyang** [comment]
As of suggestion provided [here](https://github.com/pytorch/fairseq/issues/915#issuecomment-515773561), the problem should be kind of weird ....

**Comment by chevalierNoir** [comment]
Hi,

What is the `distributed_world_size` and `nprocs_per_node` did you set in the config?

**Comment by stoneyang** [comment]
> Hi,
> 
> What is the `distributed_world_size` and `nprocs_per_node` did you set in the config?

in `av_hubert/avhubert/conf/pretrain/base_lrs3_iter1.yaml`, the two options are set as follows:
```
distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  distributed_world_size: 1
  distributed_port: 29671
  nprocs_per_node: 8
```

**Comment by chevalierNoir** [comment]
`distributed_world_size` should be set to the number of GPUs to use, which should be 8 here.

**Comment by stoneyang** [comment]
> `distributed_world_size` should be set to the number of GPUs to use, which should be 8 here.

Uh, I've tried that configuration before. When setting `distributed_world_size` other than 1, the following error would raise: 
```
[2022-02-16 14:33:42,664][fairseq.trainer][INFO] - detected shared parameter: feature_extractor_video.resnet.frontend3D.0.bias <- feature_extractor_video.resnet.trunk.layer4.1.conv2.bias
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/home/Code/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/usr/local/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/usr/local/lib/python3.8/site-packages/hydra/core/utils.py", line 129, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/Code/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/Code/av_hubert/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/Code/av_hubert/fairseq/fairseq_cli/train.py", line 138, in main
    trainer = Trainer(cfg, task, model, criterion, quantizer)
  File "/home/Code/av_hubert/fairseq/fairseq/trainer.py", line 148, in __init__
    if self.data_parallel_rank == 0:
  File "/home/Code/av_hubert/fairseq/fairseq/trainer.py", line 181, in data_parallel_rank
    return distributed_utils.get_data_parallel_rank()
  File "/home/Code/av_hubert/fairseq/fairseq/distributed/utils.py", line 463, in get_data_parallel_rank
    return get_rank(get_data_parallel_group())
  File "/home/Code/av_hubert/fairseq/fairseq/distributed/utils.py", line 405, in get_rank
    return dist.get_rank(group=group)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 688, in get_rank
    default_pg = _get_default_group()
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```
After reading [this](https://github.com/pytorch/fairseq/issues/3451#issuecomment-814181782), the `distributed_port` shoud be removed in single machine setting. And the training is now successfully started on all gpus!
