### ISSUE TITLE
pip install --editable ./

### ISSUE THREAD

**Issue by Cristian-Fioravanti** [facebookresearch/av_hubert#28]
i was doing the installtion step, and when i used "pip install --editable ./" i got this error:

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "C:\Users\floro\.conda\envs\avhubert\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\floro\.conda\envs\avhubert\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\floro\.conda\envs\avhubert\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\floro\AppData\Local\Temp\pip-build-env-k0mueac_\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\floro\AppData\Local\Temp\pip-build-env-k0mueac_\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\floro\AppData\Local\Temp\pip-build-env-k0mueac_\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 261, in <module>
          os.symlink(os.path.join("..", "examples"), fairseq_examples)
      OSError: [WinError 1314] Il privilegio richiesto non appartiene al client: '..\\examples' -> 'fairseq\\examples'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Cristian-Fioravanti** [comment]
yes there is, i tried also to do before the steps in preparation, but the error still appears

**Comment by chevalierNoir** [comment]
Were you able to install the latest version of [fairseq](https://github.com/pytorch/fairseq) following their instructions? If not, that's an issue of fairseq installation on your system and you can create an issue there.

**Comment by chke097** [comment]
@Cristian-Fioravanti  Hi, I also met the same problem as you. Have you solved it? If so, what is your solution? Thank you!

**Comment by Cristian-Fioravanti** [comment]
> @Cristian-Fioravanti Hi, I also met the same problem as you. Have you solved it? If so, what is your solution? Thank you!

i don't remember anymore sorry

**Comment by LexiconCode** [comment]
> @Cristian-Fioravanti Hi, I also met the same problem as you. Have you solved it? If so, what is your solution? Thank you!

Try running command prompt as administrator.  This is generally not recommended and do so at your own risk.  However the error points to permission issue with the file system.

**Comment by llamasrock** [comment]
> Try running command prompt as administrator. This is generally not recommended and do so at your own risk. However the error points to permission issue with the file system.

This is the solution, thank you!
