### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by YUCHEN005** [facebookresearch/av_hubert#30]
Hi author, I am finetuning the avhubert from srcatch (no pretraining, don't load pretrained models), I met this bug randomly (sometimes it work okay until trainng process finish, sometimes it bug at 7-th/8-th epoch, here it bug at 1-st epoch):

> [2022-03-05 11:27:22,366][fairseq.trainer][INFO] - begin training epoch 1
[2022-03-05 11:27:22,366][fairseq_cli.train][INFO] - Start iterating over samples
[2022-03-05 11:31:42,858][train_inner][INFO] - {"epoch": 1, "update": 0.126, "loss": "164.307", "nll_loss": "8.41", "total": "362.38", "n_correct": "23.52", "ppl": "340.12", "accuracy": "6.49", "wps": "407.1", "ups": "1.12", "wpb": "362.4", "bsz": "19.1", "num_updates": "200", "lr": "2.98e-05", "gnorm": "63.672", "loss_scale": "128", "train_wall": "175", "gb_free": "38", "wall": "262"}
Traceback (most recent call last):
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 
>
> -- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq_cli/train.py", line 287, in train
    for i, samples in enumerate(progress):
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/logging/progress_bar.py", line 191, in __iter__
    for i, obj in enumerate(self.iterable, start=self.n):
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 56, in __next__
    x = next(self._itr)
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 509, in _chunk_iterator
    for x in itr:
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 56, in __next__
    x = next(self._itr)
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 637, in __next__
    raise item
  File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 567, in run
    for item in self._source:
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/hubert_dataset.py", line 349, in __getitem__
    video_feats, audio_feats = self.load_feature(self.names[index])
  File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/hubert_dataset.py", line 277, in load_feature
    video_feats = self.load_video(video_fn) # [T, H, W, 1]
  File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/hubert_dataset.py", line 299, in load_video
    feats = custom_utils.load_video(os.path.join(self.audio_root, audio_name))
  File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/utils.py", line 23, in load_video
    frames = np.stack(frames)
  File "<__array_function__ internals>", line 6, in stack
  File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
>
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> Ended (code 256) at Sat Mar  5 11:37:54 +08 2022, elapsed time 799 seconds

It seems that bug exists during the video data loading, so I wonder if it is problem of any package version (like numpy)? 

My conda env is: torch-1.9.1, python-3.7.10, numpy-1.20.2.

Hope you can help me, thank you very much!

**Comment by YUCHEN005** [comment]
> Hi author, I am finetuning the avhubert from srcatch (no pretraining, don't load pretrained models), I met this bug randomly (sometimes it work okay until trainng process finish, sometimes it bug at 7-th/8-th epoch, here it bug at 1-st epoch):
> 
> > [2022-03-05 11:27:22,366][fairseq.trainer][INFO] - begin training epoch 1
> > [2022-03-05 11:27:22,366][fairseq_cli.train][INFO] - Start iterating over samples
> > [2022-03-05 11:31:42,858][train_inner][INFO] - {"epoch": 1, "update": 0.126, "loss": "164.307", "nll_loss": "8.41", "total": "362.38", "n_correct": "23.52", "ppl": "340.12", "accuracy": "6.49", "wps": "407.1", "ups": "1.12", "wpb": "362.4", "bsz": "19.1", "num_updates": "200", "lr": "2.98e-05", "gnorm": "63.672", "loss_scale": "128", "train_wall": "175", "gb_free": "38", "wall": "262"}
> > Traceback (most recent call last):
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
> > distributed_utils.call_main(cfg, pre_main)
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/distributed/utils.py", line 351, in call_main
> > join=True,
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
> > return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
> > while not context.join():
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
> > raise ProcessRaisedException(msg, error_index, failed_process.pid)
> > torch.multiprocessing.spawn.ProcessRaisedException:
> > -- Process 0 terminated with the following error:
> > Traceback (most recent call last):
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
> > fn(i, *args)
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
> > main(cfg, **kwargs)
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq_cli/train.py", line 180, in main
> > valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/contextlib.py", line 74, in inner
> > return func(*args, **kwds)
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq_cli/train.py", line 287, in train
> > for i, samples in enumerate(progress):
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/logging/progress_bar.py", line 191, in **iter**
> > for i, obj in enumerate(self.iterable, start=self.n):
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 56, in **next**
> > x = next(self._itr)
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 509, in _chunk_iterator
> > for x in itr:
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 56, in **next**
> > x = next(self._itr)
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 637, in **next**
> > raise item
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/fairseq/fairseq/data/iterators.py", line 567, in run
> > for item in self._source:
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in **next**
> > data = self._next_data()
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
> > return self._process_data(data)
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
> > data.reraise()
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
> > raise self.exc_type(msg)
> > ValueError: Caught ValueError in DataLoader worker process 5.
> > Original Traceback (most recent call last):
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
> > data = fetcher.fetch(index)
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in 
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/hubert_dataset.py", line 349, in **getitem**
> > video_feats, audio_feats = self.load_feature(self.names[index])
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/hubert_dataset.py", line 277, in load_feature
> > video_feats = self.load_video(video_fn) # [T, H, W, 1]
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/hubert_dataset.py", line 299, in load_video
> > feats = custom_utils.load_video(os.path.join(self.audio_root, audio_name))
> > File "/home3/huyuchen/pytorch_workplace/av_hubert/avhubert/utils.py", line 23, in load_video
> > frames = np.stack(frames)
> > File "<**array_function** internals>", line 6, in stack
> > File "/home3/huyuchen/anaconda3/envs/avhubert/lib/python3.7/site-packages/numpy/core/shape_base.py", line 423, in stack
> > raise ValueError('need at least one array to stack')
> > ValueError: need at least one array to stack
> > Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> > Ended (code 256) at Sat Mar  5 11:37:54 +08 2022, elapsed time 799 seconds
> 
> It seems that bug exists during the video data loading, so I wonder if it is problem of any package version (like numpy)?
> 
> My conda env is: torch-1.9.1, python-3.7.10, numpy-1.20.2.
> 
> Hope you can help me, thank you very much!

I repeat the experiment again, and failed at 3-rd epoch, the bug happened while loading the video sample "trainval/ramueKMLXZY/50004.mp4", but I check this sample, it's okay, and it also works during the first 2 epochs. 

I get really confused...

**Comment by chevalierNoir** [comment]
Hi,

This is possibly an issue with opencv video loading. We occasionally have the issue too. As a temporary workaround, you can reload the video once it fails like the following in [this function](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/utils.py#L14-L25) :

```
for i in range(3):
    try:
        ## load video
        return load_video(path)
    except Exception:
        print(f"failed loading {path} ({i} / 3)")
        if i == 2:
            raise ValueError(f"Unable to load {path}")
```

We will update it soon.

**Comment by YUCHEN005** [comment]
Got it, thank you for help.
