### ISSUE TITLE
ValueError: Cannot register duplicate model (av_hubert)

### ISSUE THREAD

**Issue by muxiddin19** [facebookresearch/av_hubert#36]
When I run code from "2. Inference with the model", I faced this issue. Can you give me some solutions, please?

**Comment by chevalierNoir** [comment]
Did you run within a notebook or not? If you run within the notebook, can you show your code for "2. Inference with the model", as below? 
<img width="1254" alt="avhubert-vsr-block2" src="https://user-images.githubusercontent.com/11796408/159537012-28e3e860-8210-47b1-96a7-d179c9a8ebbc.png">

**Comment by zuujhyt** [comment]
Hi I met the same error. I didn't run it inside the colab. I ran it in the terminal.
```colab_extract_visual_feature.py``` is 
```
import cv2
import tempfile
import torch
import utils as avhubert_utils
from argparse import Namespace
import fairseq
from fairseq import checkpoint_utils, options, tasks, utils
from IPython.display import HTML

def extract_visual_feature(video_path, ckpt_path, user_dir, is_finetune_ckpt=False):
  utils.import_user_module(Namespace(user_dir=user_dir))
  models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
  transform = avhubert_utils.Compose([
      avhubert_utils.Normalize(0.0, 255.0),
      avhubert_utils.CenterCrop((task.cfg.image_crop_size, task.cfg.image_crop_size)),
      avhubert_utils.Normalize(task.cfg.image_mean, task.cfg.image_std)])
  frames = avhubert_utils.load_video(video_path)
  print(f"Load video {video_path}: shape {frames.shape}")
  frames = transform(frames)
  print(f"Center crop video to: {frames.shape}")
  frames = torch.FloatTensor(frames).unsqueeze(dim=0).unsqueeze(dim=0).cuda()
  model = models[0]
  if hasattr(models[0], 'decoder'):
    print(f"Checkpoint: fine-tuned")
    model = models[0].encoder.w2v_model
  else:
    print(f"Checkpoint: pre-trained w/o fine-tuning")
  model.cuda()
  model.eval()
  with torch.no_grad():
    # Specify output_layer if you want to extract feature of an intermediate layer
    feature, _ = model.extract_finetune(source={'video': frames, 'audio': None}, padding_mask=None, output_layer=None)
    feature = feature.squeeze(dim=0)
  print(f"Video feature shape: {feature.shape}")
  return feature

mouth_roi_path, ckpt_path = "../data/roi.mp4", "../data/finetune-model.pt"
user_dir = "/home/xiikjuy/test/av_hubert/avhubert"
feature = extract_visual_feature(mouth_roi_path, ckpt_path, user_dir)

```

cd /home/jchou/test/av_hubert/avhubert
python colab_extract_visual_feature.py
I get error:
```
Traceback (most recent call last):
  File "colab_extract_visual_feature.py", line 39, in <module>
    feature = extract_visual_feature(mouth_roi_path, ckpt_path, user_dir)
  File "colab_extract_visual_feature.py", line 11, in extract_visual_feature
    utils.import_user_module(Namespace(user_dir=user_dir))
  File "/home/xiikjuy/test/av_hubert/fairseq/fairseq/utils.py", line 482, in import_user_module
    importlib.import_module(module_name)
  File "/home/xiikjuy/miniconda3/envs/avhubert/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xiikjuy/test/av_hubert/avhubert/__init__.py", line 7, in <module>
    from .hubert_asr import *  # noqa
  File "/home/xiikjuy/test/av_hubert/avhubert/hubert_asr.py", line 27, in <module>
    from hubert import AVHubertModel
  File "/home/xiikjuy/test/av_hubert/avhubert/hubert.py", line 335, in <module>
    class AVHubertModel(BaseFairseqModel):
  File "/home/xiikjuy/test/av_hubert/fairseq/fairseq/models/__init__.py", line 121, in register_model_cls
    raise ValueError("Cannot register duplicate model ({})".format(name))
ValueError: Cannot register duplicate model (av_hubert)

```
Any advice?
thank you.

**Comment by chevalierNoir** [comment]
Just append some dummy argument to your command: `python colab_extract_visual_feature.py dummy`. For debugging purpose, we treat it as a special mode when there is no argument like [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert.py#L28]).

**Comment by zuujhyt** [comment]
it works, thanks.

**Comment by shakeel608** [comment]
Incase you already have parse arguments, passing dummy will throw error "error: unrecognized arguments: dummy". Just by adding
`    parser.add_argument('--dummy', type=str, default=None, help='A dummy argument for future use.')
`
will solve the issue

**Comment by shami09** [comment]
Yes it works, I faced this problem too. You need to keep changing the dummy argument
