### ISSUE TITLE
Convert AV-HuBERT Model into ONNX Format

### ISSUE THREAD

**Issue by xuan97916** [facebookresearch/av_hubert#44]
Hi, thanks for your great work! I'm trying to export AV-HuBERT model (.pt format) to .onnx format like this:
```python
models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task([cfg.common_eval.path])
export_model = models[0].eval()
dummy_input = {'source': {'audio': torch.zeros(1, 104, 500),
                          'video': torch.zeros(1, 1, 500, 112, 112)},
                          'padding_mask': torch.full((1, 500), False)}
torch.onnx.export(export_model, 
                  dummy_input, 
                  './test.onnx',
                  opset_version=10,
                  do_constant_folding=True,
                  input_names=['input'],
                  output_names=['output'])
```
But received this error:
```python
/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/onnx/utils.py:363: UserWarning: Skipping _decide_input_format
 -1
  warnings.warn("Skipping _decide_input_format\n {}".format(e.args[0]))
Traceback (most recent call last):
  File "/home/offset/Downloads/pycharm-community-2021.3.1/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/offset/conda/envs/avhubert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 1 positional argument but 2 were given
```
Is it right to use `torch.onnx.export()` to export the model to onnx format? I have noticed `prepare_for_onnx_export_()` in fairseq source code, but I have no idea how to use it.

Thanks in advance for your comment!

All the best,
An Hsu

**Comment by chevalierNoir** [comment]
Hi,

We haven't exported the model to OONX format before. But it should be similar to other fairseq models like [wav2vec](https://github.com/pytorch/fairseq/issues/3010).
