### ISSUE TITLE
pretrain log issue

### ISSUE THREAD

**Issue by li563042811** [facebookresearch/av_hubert#61]
Hi,
   I found a bug when I pretrained av-hubert using LRS3 data. It's in hubert_criterion.py line 112.
----------------------------------------------   
 with torch.no_grad():
            for i, logp_m in enumerate(logp_m_list):
                # corr_m, count_m = compute_correct(logp_m)
                if logp_m.numel() == 0:
                    corr_m, count_m = 0
---------------------------------------------
  I think 
corr_m, count_m = 0 
should be 
corr_m, count_m = 0, 0
or it will come to this error.
---------------------------------------------
Traceback (most recent call last):
  File "/lustre_data/lichao/env/miniconda3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/lustre_data/lichao/code/AVSR/av-hubert/av_hubert/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/lustre_data/lichao/code/AVSR/av-hubert/av_hubert/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/lustre_data/lichao/env/miniconda3.8/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/lustre_data/lichao/code/AVSR/av-hubert/av_hubert/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/lustre_data/lichao/env/miniconda3.8/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/lustre_data/lichao/code/AVSR/av-hubert/av_hubert/fairseq/fairseq/trainer.py", line 707, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/lustre_data/lichao/code/AVSR/av-hubert/av_hubert/fairseq/fairseq/tasks/fairseq_task.py", line 502, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/lustre_data/lichao/env/miniconda3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lustre_data/lichao/code/AVSR/av-hubert/av_hubert/avhubert/hubert_criterion.py", line 112, in forward
    corr_m, count_m = 0
TypeError: cannot unpack non-iterable int object
-----------------------------------------------------------

**Comment by chevalierNoir** [comment]
Thank you for finding the bug and we will fix this in the code. By the way, which config file did you use in the pretraining? This shouldn't be triggered when masking probability is set to non-zero.

**Comment by li563042811** [comment]
> Thank you for finding the bug and we will fix this in the code. By the way, which config file did you use in the pretraining? This shouldn't be triggered when masking probability is set to non-zero.
This is the config file for my 1st iteration pretraining. The modality_dropout is 0.
[base_lrs3_iter1.yaml](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/conf/pretrain/base_lrs3_iter1.yaml)

**Comment by li563042811** [comment]
This is the config file I used in 1st pretrain iteration and the modality_dropout is 0.
[base_lrs3_iter1.yaml](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/conf/pretrain/base_lrs3_iter1.yaml)

**Comment by li563042811** [comment]
This is the config file I used in the 1st pretrain iteration. Is this the right file to use in the 1st iteration?
https://github.com/facebookresearch/av_hubert/blob/main/avhubert/conf/pretrain/base_lrs3_iter1.yaml

**Comment by chevalierNoir** [comment]
Yes. It is the correct config file for 1st iter in LRS3 pretraining.

**Comment by li563042811** [comment]
> Yes. It is the correct config file for 1st iter in LRS3 pretraining.

Hi, thanks for your reply. I have a question about pertaining. 
After I finish the 1st iteration, should I start the 2nd iteration based on the checkpoint_last.pt of the 1st iteration or start with randomly initialized parameters?

**Comment by chevalierNoir** [comment]
Hi,

The 2nd iteration is started with random initialization.
