### ISSUE TITLE
Loading Finetuned Models for Visual Speech Recognition: Could not infer model type 'av_hubert_seq2seq'

### ISSUE THREAD

**Issue by david-gimeno** [facebookresearch/av_hubert#63]
Hello,

I was trying to load a finetuned model for the VSR task. I followed the indications on the repository and the jupyter notebook (below you can see that I tried to import modules from the avhubert path). I copy my script:

import fairseq
from argparse import Namespace
from fairseq import checkpoint_utils, options, tasks, utils
import hubert_pretraining, hubert

def load_model(ckpt_path, user_dir):
    #utils.import_user_module(Namespace(user_dir=user_dir))
    models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
    #model = models[0]
    #print(model)

if __name__ == "__main__":
   user_dir="../../av_hubert/avhubert/"
   ckpt_path = "./base_vox_433h.pt"

   load_model(ckpt_path, user_dir)

**I run the script and then, I got the following error:**

"""
...
models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/checkpoint_utils.py", line 446, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/models/__init__.py", line 88, in build_model
    assert model is not None, (
AssertionError: Could not infer model type from {'_name': 'av_hubert_seq2seq', 'w2v_path': '/check ...

...

Available models: dict_keys(['wav2vec', 'wav2vec2', 'wav2vec_ctc', 'wav2vec_seq2seq', 'hubert', 'hubert_ctc', 'transformer_lm', 'av_hubert']) 
Requested model type: av_hubert_seq2seq
"""

How should I load a model for VSR? Thanks in advance,

David.

**Comment by chevalierNoir** [comment]
Hi,

To load a finetuned model, you should import hubert_asr: `import hubert_asr`.

**Comment by david-gimeno** [comment]
Thank you so much! It solved the problem. But, now I would like to ask you where I can find the pretrained CTC Linear Layer, I mean, the layer that process the encoder's output to get the CTC scores. I am getting lost in the source code.

**Comment by chevalierNoir** [comment]
1. The tokenizer is saved in the fine-tuning checkpoint and will be loaded when you run inference.
2.  In our paper, we tried two types of fine-tuning: (a) CTC, (b) S2S, where S2S outperforms CTC. In the repo, we use S2S for finetuning given its better performance and simpler decoding process.

**Comment by david-gimeno** [comment]
Perfect, thank you for clarifying me these aspects. So, I run the command:

`fairseq-hydra-train --config-dir ${PWD}/conf/finetune/ --config-name base_vox_433h.yaml \
task.data=${PWD}/data/LRS3-TED/speaker-independent/ \
task.label_dir=${PWD}/data/LRS3-TED/speaker-independent/ task.tokenizer_bpe_model=/checkpoint/bshi/data/lrs3//lang/spm/spm_unigram1000.model \
model.w2v_path=${PWD}/base_vox_433h.pt \
hydra.run.dir=${PWD}/exp/LRS3-TED/ common.user_dir=${PWD}
`
But I am getting the following error, do you know which could be the reason?

`Traceback (most recent call last):
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq_cli/train.py", line 97, in main
    model = task.build_model(cfg.model)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/dgimeno/phd/av_hubert/avhubert/hubert_asr.py", line 474, in build_model
    del state['model']['mask_emb']
KeyError: 'mask_emb'`

**Comment by david-gimeno** [comment]
Thank you for clarifying these aspects!! Now, i would like to ask you how can I fine-tuned this pre-trained model. I run this command:

`fairseq-hydra-train --config-dir ${PWD}/conf/finetune/ --config-name base_vox_433h.yaml task.data=${PWD}/data/LRS3-TED/speaker-independent/ task.label_dir=${PWD}/data/LRS3-TED/speaker-independent/ task.tokenizer_bpe_model=/checkpoint/bshi/data/lrs3//lang/spm/spm_unigram1000.model model.w2v_path=${PWD}/base_vox_433h.pt hydra.run.dir=${PWD}/exp/LRS3-TED/ common.user_dir=${PWD}`

But I am getting the following error:

`Traceback (most recent call last):
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq_cli/train.py", line 97, in main
    model = task.build_model(cfg.model)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home/dgimeno/phd/av_hubert/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/dgimeno/phd/av_hubert/avhubert/hubert_asr.py", line 474, in build_model
    del state['model']['mask_emb']
KeyError: 'mask_emb'`

**Comment by chevalierNoir** [comment]
Fine-tuning a **fine-tuned model** cannot be done with simply changing the argument in the finetuning command. However, it is doable with a bit of modifications on the code. Basically, you should load the fine-tuned model weights to your model at initialization by adding the following code at [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert_asr.py#L413-L416):

```
state = checkpoint_utils.load_checkpoint_to_cpu(cfg.ft_ckpt_path)  
self.load_state_dict(state["model"])
```

where `cfg.ft_ckpt_path` is the path of the fine-tuned model, which you should add to the [configuration](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert_asr.py#L194):
```
ft_ckpt_path: str = field(default="", metadata={"help": "path to the finetuned checkpoint"})
```

Now, use the original command by appending `+model.ft_ckpt_path=/path/to/finetune-checkpoint`. Note the dimension of some weight matrices in your new model (e.g., outptut linear projection) may differ from the fine-tuned checkpoint you use. Thus you should take care of such inconsistency in  checkpoint loading above (i.e, `self.load_state_dict(state["model"])`).

**Comment by david-gimeno** [comment]
I really appreciate everything you did for me. Thank you so much! As you indicated, the output linear projection layer had to be considered when loading the pre-trained parameters, since I suspect that, depending on the database used (above all if you are dealing with other language, as it is my case), the optimal vocabulary size of the tokenizer may be different. So, in order to solve this issue and taking into account your previous code, I implement the following at [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/hubert_asr.py#L413-L416):

`state = checkpoint_utils.load_checkpoint_to_cpu(cfg.ft_ckpt_path)

        for key in state["model"].copy().keys():
            if key in ["decoder.embed_tokens.weight", "decoder.embed_out"]:
                state["model"].pop(key, None)

        self.load_state_dict(state["model"], strict=False)
        print("\nAVHubertSeq2Seq loaded from", cfg.ft_ckpt_path, "\n")`

This allow us to load a fine-tuned VSR model based on AVHuBERT. So, we are able to re-estimated this VSR model to other database than LRS3-TED corpus, since the loading process discards the output linear projection whose dimension depends on the vocabulary size defined by the tokenizer.

Now, I only have to find out which is the best configuration to get state-of-the-art results on my database :) Time will tell. Thanks again. Best regards from Spain,

David.

**Comment by nobel861017** [comment]
Do we still have to provide the `model.w2v_path` parameter in the command?
