### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by BDHU** [facebookresearch/av_hubert#67]
When I try to prepare the data in step 2 with the command: `python lrs3_prepare.py --lrs3 ${lrs3} --ffmpeg $(which ffmpeg) --rank ${rank} --nshard ${nshard} --step 2`, it shows:

```text
Traceback (most recent call last):
  File "lrs3_prepare.py", line 236, in <module>
    trim_pretrain(args.lrs3, args.ffmpeg, args.rank, args.nshard, step=args.step)
  File "lrs3_prepare.py", line 181, in trim_pretrain
    trim_audio(csv_fn, pretrain_dir, output_audio_dir, ffmpeg, rank, nshard)
  File "lrs3_prepare.py", line 155, in trim_audio
    raw_audio = AudioSegment.from_wav(wav_path)
  File "/opt/conda/lib/python3.8/site-packages/pydub/audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
  File "/opt/conda/lib/python3.8/site-packages/pydub/audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "/opt/conda/lib/python3.8/site-packages/pydub/utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpn2344vft/tmp.wav'
```

**Comment by chevalierNoir** [comment]
Hi,

This is probably because your ffmpeg failed to generate audio wav file from the video (see [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/preparation/lrs3_prepare.py#L152-L153)), which may be due to using an incompatible version of ffmpeg.  You could remove the argument ` ' -loglevel quiet'` in the above lines when using ffmpeg such that a more detailed error message can be shown.

**Comment by BDHU** [comment]
I figured out the problem, it was missing video files. Closing this.
