### ISSUE TITLE
preparation-cnn_face_detector

### ISSUE THREAD

**Issue by sungheedong** [facebookresearch/av_hubert#71]
Hi.

I'm doing preparation using dlib and avhubert/preparation
First I installed dlib via "yum install" and then downloaded python_examples in dlib github page.

I run python3 detect_landmark.py --root ../LRS3 --landmark ../LRS3/landmark --manifest ../LRS3/file.list.org --cnn_detector ../dlib/python_examples/cnn_face_detector.py --face_predictor ../dlib/python_examples/face_detector.py --ffmpeg /bin/ffmpeg --rank 1 --nshard 2

Then,
I got the following error message, 

Traceback (most recent call last):
  File "detect_landmark.py", line 72, in <module>
   detect_face_landmarks(args.face_predictor, args.cnn_detector, args.root, args.landmark, args.manifest, args.rank, args.nshard)
  File "detect_landmark.py", line 34, in detect_face_landmarks
    cnn_detector = dlib.cnn_face_detection_model_v1(cnn_detector_path)
RuntimeError: An error occurred while trying to read the first object from the file '/home/dsh/dlib/python_examples/cnn_face_detector.py'.
ERROR: Unexpected version found while deserializing dlib::add_loss_layer.

How can I solve the problem?
Please help.

Thank you.

**Comment by chevalierNoir** [comment]
Hi,

Did you try installing dlib directly with `pip install -r requirements.txt`, where `requirements.txt` is [here](https://github.com/facebookresearch/av_hubert/blob/main/avhubert/preparation/requirements.txt).

**Comment by s2485523800** [comment]
Hi.
Have you already solved this problem?  What did you do

Please help.

Thank you.
