### ISSUE TITLE
 Job not requeued because: timed-out and not checkpointable?

### ISSUE THREAD

**Issue by l349074299** [facebookresearch/av_hubert#9]
When i prepare data ,and use "python count_frames.py"command ,error occur:

(avhubert) dragon@dragon-System-Product-Name:~/Project/av_hubert/avhubert/preparation$ python count_frames.py --root /data/dataset/LRS3/ --manifest /data/dataset/LRS3/test_list.txt --nshard 1 \
> --slurm_partition cpu
Traceback (most recent call last):
  File "count_frames.py", line 43, in <module>
    fids = [ln.strip() for ln in open(args.manifest).readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/data/dataset/LRS3/test_list.txt'
^C
(avhubert) dragon@dragon-System-Product-Name:~/Project/av_hubert/avhubert/preparation$ python count_frames.py --root /data/dataset/LRS3/ --manifest /data/dataset/LRS3/file_finetune.list --nshard 1 --slurm_partition cpu
33303 files
Traceback (most recent call last):
  File "count_frames.py", line 68, in <module>
    num_frames = [job.result() for job in jobs]
  File "count_frames.py", line 68, in <listcomp>
    num_frames = [job.result() for job in jobs]
  File "/home/dragon/anaconda3/envs/avhubert/lib/python3.8/site-packages/submitit/core/core.py", line 264, in result
    r = self.results()
  File "/home/dragon/anaconda3/envs/avhubert/lib/python3.8/site-packages/submitit/core/core.py", line 292, in results
    raise job_exception  # pylint: disable=raising-bad-type
submitit.core.utils.FailedJobError: Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/dragon/anaconda3/envs/avhubert/lib/python3.8/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/home/dragon/anaconda3/envs/avhubert/lib/python3.8/site-packages/submitit/core/utils.py", line 122, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "count_frames.py", line 19, in count_frames
    num_frames_audio = len(wavfile.read(wav_fn)[1])
  File "/home/dragon/anaconda3/envs/avhubert/lib/python3.8/site-packages/scipy/io/wavfile.py", line 547, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/home/dragon/anaconda3/envs/avhubert/lib/python3.8/site-packages/scipy/io/wavfile.py", line 437, in _read_riff_chunk
    str1 = fid.read(4)  # File signature
  File "/home/dragon/anaconda3/envs/avhubert/lib/python3.8/site-packages/submitit/core/job_environment.py", line 211, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: **Job not requeued because: timed-out and not checkpointable.**

**Comment by l349074299** [comment]
when I set **"executor.update_parameters(slurm_array_parallelism=100, slurm_partition=args.slurm_partition,timeout_min=int(2 * 60),)"** in **"count_frames.py"**
it work!!!
